class PagesController < ApplicationController

  def glossaire
    @alphabet = ('A'..'Z').to_a
    glossary_hash
  end

  private

  def glossary_hash
    @glossary = {}
    @glossary["AERAS"] = "Acronyme de s’Assurer et Emprunter avec un Risque Aggravé de Santé, c’est un dispositif conventionnel appliqué automatiquement par l'ensemble des banques et des assureurs qui proposent une assurance emprunteur. Il permet à une personne présentant ou ayant présenté un risque aggravé de santé d'obtenir à des conditions spécifiques un prêt immobilier qu'elle ne pourrait pas obtenir dans les conditions standards d'assurance."
    @glossary["Amiante"] = "Est un terme désignant certains minéraux à texture fibreuse utilisés dans l’industrie. Il a attiré l'attention de certains industriels à la fin du XIXe siècle pour sa résistance à la chaleur, au feu, à la tension, aux agressions électriques et chimiques, ainsi que pour son pouvoir absorbant. L'amiante constitue, aujourd’hui, un problème majeur de santé publique et de santé au travail : massivement utilisé, il s’est révélé hautement toxique et le nombre de maladies graves qu'il a induit ne cesse d'augmenter. Interdit en France depuis 1997, il reste présent dans de nombreux bâtiments et équipements. Pour être retiré, il nécessite l’intervention d’une entreprise spécialisée, détentrice de la certification nationale et titulaire d'une assurance professionnelle : c’est ce qu’on appelle le désamiantage."
    @glossary["Amortissement"] = "Dans le langage financier, l'amortissement est l'opération consistant au remboursement en totalité ou en partie d'un crédit bancaire ou d'un emprunt obligataire."
    @glossary["Article 1641"] = "Le vendeur est tenu de la garantie à raison des défauts cachés de la chose vendue qui la rendent impropre à l'usage auquel on la destine, ou qui diminuent tellement cet usage que l'acheteur ne l'aurait pas acquise, ou n'en aurait donné qu'un moindre prix, s'il les avait connus. Article du code Civil qui détermine les contours de la garantie des vices cachés à la charge du vendeur."
    @glossary["Banque"] = "Etablissement financier qui, recevant des fonds du public, les emploie pour effectuer des opérations de crédit et des opérations financières, et est chargé de l'offre et de la gestion des moyens de paiement."
    @glossary["Bouquet"] = "Il s'agit du capital versé le jour de l'achat d'un bien en viager. Le reste de la valeur du bien prend la forme d'une rente."
    @glossary["Cadastre"] = "Ensemble des documents établis à la suite de relevés topographiques et d'opérations administratives, et destinés à permettre la détermination des propriétés foncières d'un territoire, la constatation de la nature de leurs produits et l'évaluation de leur revenu. C’est aussi le nom de l’administration qui a la charge de ces documents."
    @glossary["Carnet d'entretien"] = "Tout immeuble en copropriété doit posséder un carnet d'entretien. Ce document répertorie des informations techniques sur la maintenance et les travaux effectués dans l'immeuble. Il doit être réalisé, tenu et mis à jour par le syndic de copropriété."
    @glossary["CCMI"] = "Le Contrat de Construction de Maison Individuelle a été créé afin de protéger les particuliers de certains constructeurs douteux. C’est le contrat le plus utilisé dans la construction de maison individuelle. Il est fortement recommandé d’en signer un afin d’obtenir les garanties encadrées par la réglementation française. Il est obligatoire lorsque le terrain n’appartient pas au constructeur et que celui-ci est en charge de la réalisation d’un ou deux logements, destinés au même acquéreur. Véritable protection pour les maitres d’ouvrage, le CCMI offre également des garanties de livraison, de prix et des délais."
    @glossary["Certificat de conformité"] = "la construction d’un bien immobilier nécessite le dépôt et l’obtention d’un permis de construire auprès de la mairie. Les travaux doivent alors être conformes au permis de construire en question et respecter les règles d'urbanisme en vigueur. La mairie peut effectuer un contrôle et délivrer un certificat de conformité si aucune anomalie n'est détectée. Le certificat de conformité n’est pas systématiquement obligatoire, seuls certains travaux le nécessitent. C’est par exemple le cas lorsque ces derniers concernent un immeuble classé monument historique ou encore une construction située dans un secteur sauvegardé."
    @glossary["Charges générales"] = "Charges payées par la totalité des copropriétaires, sans exception, et sans intervention de la notion d'utilité : honoraires de syndic, assurance de l'immeuble, entretien des espaces verts…"
    @glossary["Charges récupérables"] = "Aussi appelées charges locatives, ce sont des dépenses prises en charges initialement par le propriétaire, mais que celui-ci peut se faire rembourser par le locataire. Elles sont réglementairement définies. Le paiement s'effectue soit par le versement de provisions pour charges avec une régularisation annuelle, soit par la récupération ponctuelle des dépenses engagées."
    @glossary["Charges spéciales"] = "Charges entraînées par les services collectifs et les éléments d'équipements communs (article 10 de la loi du 10 juillet 1965). Elles sont payées par les seuls copropriétaires qui ont l'utilité de ces services et équipements."
    @glossary["Clause résolutoire"] = "Clause d'un contrat prévoyant à l'avance sa résiliation automatique dans le cas où l'une des parties ne respecte pas une de ses obligations contractuelles. La partie qui a commis ce manquement ne peut alors pas contester cette résiliation devant les tribunaux. Celle-ci se retrouve fréquemment notamment dans les contrats de bail : une clause peut par exemple prévoir la résiliation du celui-ci lorsque le locataire ne paye pas son loyer."
    @glossary["Clauses suspensives"] = "Ce sont les conditions que l’on peut les retrouver dans les contrats qui précèdent la vente d'un logement, les conditions suspensives suspendent les effets de l'avant-contrat jusqu'à l'arrivée d'un terme futur et incertain. Si ce dernier ne se réalise pas dans le délai convenu, la promesse devient nulle et les parties sont libérées de leurs obligations."
    @glossary["Compte séquestre"] = "C’est un compte bancaire qui est sous le contrôle d'une tierce partie. Il est souvent utilisé par les acheteurs et les vendeurs pour les transactions immobilières. Le vendeur prend le dépôt de l'acheteur et ouvre un compte séquestre auprès d'une banque, d’un agent fiduciaire ou d'une compagnie immobilière. Le dépositaire légal supervise la fermeture et s'assure que tout le monde est payé convenablement. Il est également possible de créer un compte séquestre si un propriétaire refuse de faire des réparations dans votre logement ou si vous voulez un compte dédié au paiement des factures non mensuelles."
    @glossary["Conseil syndical de copropriété"] = "Il est composé de membres élus de la copropriété. Il coordonne les relations entre le syndic et copropriétaires et assure une mission consultative, d'assistance et de contrôle du syndic. Les membres du conseil syndical ne sont pas rémunérés et sont élus pour un mandat qui ne peut excéder trois ans renouvelables."
    @glossary["Contrat de réservation"] = "Lorsque le vendeur ou le promoteur et l'acquéreur sont parvenus à un accord sur une vente, ils peuvent signer un contrat de réservation avant la signature de l'acte de vente définitif. Ce document n'est pas obligatoire, mais il est recommandé pour exprimer l'accord mutuel du vendeur et de l'acquéreur et déterminer les conditions précises dans lesquelles la vente du logement s'effectuera."
    @glossary["Copropriété"] = "C’est l'organisation d'un immeuble bâti, ou d’un groupe d'immeubles bâtis, dont la propriété est répartie entre plusieurs personnes, par lots comprenant chacun une partie privative et une quote-part des parties communes."
    @glossary["Coutier"] = "Le courtier est le professionnel effectuant l'activité de courtage. Son action consiste à servir d'intermédiaire pour une transaction entre un vendeur et un acheteur, dont il est à tout moment indépendant. La transaction peut porter sur toute opération d'achat ou de vente de marchandise ou de prestation de service."

    @glossary
  end
end
